version: "3.7"
services:
#  app:
#    build:
#      context: .
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql_db
#    links:
#      - mysql_db:app_db
#    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: Pessoa
      MYSQL_ROOT_PASSWORD: root




